security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:             fos_user_security_login
                check_path:             fos_user_security_check
                always_use_default_target_path: false
                default_target_path:            home
            logout:
                path:   fos_user_security_logout
                target: home
            anonymous:  true

    access_control:
        - { path: ^/%available_locale%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%available_locale%/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%available_locale%/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%available_locale%/ajax, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/%available_locale%/admin/, role: ROLE_ADMIN }
