fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
    requirements:
        _locale: '%available_locale%'
    defaults: { _locale: '%locale%'}

fos_user_security_logout:
    path:      /logout
    defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }